# This file was generated by GoReleaser. DO NOT EDIT.
cask "n8nctl-cli" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "b608417c44572063cfec62e6b94db1aa7ecc53af5a8aedf885fa16c5b9a5fa2e"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e195eb3b9db8a98c5483f6e65cdfb8c25575948ca62417ceb3a6743a35e12f4d"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "39995f604d201d5b53516ffa68ed0420b522cdaa79a2afe9da2ac885a3d85686"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "950fddec58f4afe3944e9c267a83fc7c620a2210dddd8e5e2c0276adf93a961c"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "n8nctl-cli"
  desc "Command-line interface for the n8n workflow automation API"
  homepage "https://github.com/jjuanrivvera/n8n-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "n8nctl"
  bash_completion "completions/n8nctl.bash"
  fish_completion "completions/n8nctl.fish"
  zsh_completion "completions/n8nctl.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/n8nctl"]
    end
  end

  # No zap stanza required

end
