# This file was generated by GoReleaser. DO NOT EDIT.
cask "n8nctl-cli" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "8bcc705bc59ab9df0088a7ed43c613d40de0562ee276e17b8e2bde279a7ace27"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cff1d904d875f8d3e2d512bb0fa14415d88a204bf9205ea47c0710db26770800"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a08c9823048ecabfd9324d2cd1588c203207bde5d88ea3de06f89d1d13df2dbb"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c027bc476d17f778aad6e04fa4943652e368b110131ec768b75d89a2bca95dd"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "n8nctl-cli"
  desc "Command-line interface for the n8n workflow automation API"
  homepage "https://github.com/jjuanrivvera/n8n-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "n8nctl"
  bash_completion "completions/n8nctl.bash"
  fish_completion "completions/n8nctl.fish"
  zsh_completion "completions/n8nctl.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/n8nctl"]
    end
  end

  # No zap stanza required

end
