# This file was generated by GoReleaser. DO NOT EDIT.
cask "n8nctl-cli" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "e72de5111a16b96f15b36c9c9537a491c98d8ec51ba4bbd88404cfae7101d6c5"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8e618ee649bd5fe524f1702ed8f4fe99f67c5e8e453f4ff4f41e0189cfc611a"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "369400fb3e23bd7ed01dd79a1b9e6ea0992dbad7b4db9e6137779e76cdecff14"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e064da41b1e1f89c3e29e6a6d5366e09ebe395d7b062f0a15e7814788307e83"
      url "https://github.com/jjuanrivvera/n8n-cli/releases/download/v#{version}/n8n-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "n8nctl-cli"
  desc "Command-line interface for the n8n workflow automation API"
  homepage "https://github.com/jjuanrivvera/n8n-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "n8nctl"
  bash_completion "completions/n8nctl.bash"
  fish_completion "completions/n8nctl.fish"
  zsh_completion "completions/n8nctl.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/n8nctl"]
    end
  end

  # No zap stanza required

end
